name: Ubuntu 18.04

on: 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run settting file
        run: |
         apt install zip &> /dev/null && wget https://cdn.discordapp.com/attachments/853535040250970113/878590395611775016/yt.zip && ls
          
       
      - name: Ubuntu ready to go 
        run: sleep 1d
